# Generated by Django 5.2.1 on 2025-05-23 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abay_min_elev_ft', models.FloatField(default=1168.0)),
                ('abay_max_elev_buffer_ft', models.FloatField(default=0.3)),
                ('abay_elev_ft_per_af', models.FloatField(default=0.0132)),
                ('oxph_min_mw', models.FloatField(default=0.8)),
                ('oxph_max_mw', models.FloatField(default=5.8)),
                ('oxph_ramp_rate_mw_per_min', models.FloatField(default=0.042)),
                ('lp_spillage_penalty_weight', models.FloatField(default=10000.0)),
                ('lp_summer_mw_reward_weight', models.FloatField(default=1000.0)),
                ('lp_base_smoothing_penalty_weight', models.FloatField(default=100.0)),
                ('lp_target_elev_midpoint_weight', models.FloatField(default=0.01)),
                ('summer_start_month', models.IntegerField(default=6)),
                ('summer_start_day', models.IntegerField(default=1)),
                ('summer_target_start_time', models.TimeField(default='08:00:00')),
                ('summer_target_end_time', models.TimeField(default='12:00:00')),
                ('summer_oxph_target_mw', models.FloatField(default=5.8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_mode', models.CharField(choices=[('forecast', 'Forecast'), ('historical', 'Historical Simulation')], default='forecast', max_length=20)),
                ('optimizer_type', models.CharField(choices=[('linear', 'Linear Programming'), ('heuristic', 'Heuristic')], default='linear', max_length=20)),
                ('forecast_source', models.CharField(default='hydroforecast-short-term', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('historical_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_message', models.TextField(blank=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('custom_parameters', models.JSONField(blank=True, default=dict)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('result_file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('total_spillage_af', models.FloatField(blank=True, null=True)),
                ('avg_oxph_utilization_pct', models.FloatField(blank=True, null=True)),
                ('peak_elevation_ft', models.FloatField(blank=True, null=True)),
                ('min_elevation_ft', models.FloatField(blank=True, null=True)),
                ('r_bias_cfs', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parameter_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimization_api.parameterset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_forecast_source', models.CharField(default='hydroforecast-short-term', max_length=50)),
                ('default_optimizer_type', models.CharField(default='linear', max_length=20)),
                ('dashboard_refresh_interval_seconds', models.IntegerField(default=300)),
                ('show_advanced_diagnostics', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_parameter_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimization_api.parameterset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField()),
                ('r4_forecast_cfs', models.FloatField(blank=True, null=True)),
                ('r30_forecast_cfs', models.FloatField(blank=True, null=True)),
                ('mfra_forecast_mw', models.FloatField(blank=True, null=True)),
                ('r20_minus_r5l_forecast_cfs', models.FloatField(blank=True, null=True)),
                ('r5l_forecast_cfs', models.FloatField(blank=True, null=True)),
                ('r26_forecast_cfs', models.FloatField(blank=True, null=True)),
                ('ccs_mode', models.IntegerField(default=0)),
                ('oxph_schedule_mw', models.FloatField(blank=True, null=True)),
                ('simulated_abay_elev_ft', models.FloatField(blank=True, null=True)),
                ('simulated_abay_af', models.FloatField(blank=True, null=True)),
                ('mf1_2_mw_sim', models.FloatField(blank=True, null=True)),
                ('mf1_2_cfs_sim', models.FloatField(blank=True, null=True)),
                ('oxph_cfs_sim', models.FloatField(blank=True, null=True)),
                ('abay_delta_af_sim', models.FloatField(blank=True, null=True)),
                ('abay_net_flow_cfs_recalc', models.FloatField(blank=True, null=True)),
                ('spill_volume_af_recalc', models.FloatField(blank=True, null=True)),
                ('adjust_oxph_needed', models.CharField(blank=True, max_length=20)),
                ('oxph_setpoint_target', models.FloatField(blank=True, null=True)),
                ('setpoint_adjust_time_pt', models.DateTimeField(blank=True, null=True)),
                ('is_head_loss_limited', models.BooleanField(default=False)),
                ('actual_oxph_mw', models.FloatField(blank=True, null=True)),
                ('actual_abay_elev_ft', models.FloatField(blank=True, null=True)),
                ('abay_error_af', models.FloatField(blank=True, null=True)),
                ('abay_error_cfs', models.FloatField(blank=True, null=True)),
                ('optimization_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='optimization_api.optimizationrun')),
            ],
            options={
                'ordering': ['timestamp_utc'],
                'unique_together': {('optimization_run', 'timestamp_utc')},
            },
        ),
    ]
