# Generated by Django 5.2.1 on 2025-05-27 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded'), ('maintenance', 'Maintenance')], default='online', max_length=20)),
                ('pi_data_available', models.BooleanField(default=True)),
                ('last_pi_update', models.DateTimeField(blank=True, null=True)),
                ('optimization_available', models.BooleanField(default=True)),
                ('alert_system_active', models.BooleanField(default=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Status',
                'verbose_name_plural': 'System Status History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this alert', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('parameter', models.CharField(choices=[('afterbay_elevation', 'Afterbay Elevation (ft)'), ('oxph_power', 'OXPH Power (MW)'), ('r4_flow', 'R4 Flow (CFS)'), ('r30_flow', 'R30 Flow (CFS)'), ('r20_flow', 'R20 Flow (CFS)'), ('r5l_flow', 'R5L Flow (CFS)'), ('r26_flow', 'R26 Flow (CFS)'), ('mfra_power', 'MFRA Power (MW)'), ('float_level', 'Float Level (ft)'), ('net_flow', 'Net Flow (CFS)'), ('ccs_mode', 'CCS Mode')], help_text='Parameter to monitor', max_length=30)),
                ('condition', models.CharField(choices=[('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('equal_to', 'Equal To'), ('between', 'Between'), ('outside_range', 'Outside Range')], help_text='Alert condition', max_length=20)),
                ('threshold_value', models.FloatField(help_text='Primary threshold value')),
                ('threshold_value_max', models.FloatField(blank=True, help_text='Maximum value for range conditions', null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this alert')),
                ('email_notification', models.BooleanField(default=True, help_text='Send email notifications')),
                ('sms_notification', models.BooleanField(default=False, help_text='Send SMS notifications')),
                ('voice_notification', models.BooleanField(default=False, help_text='Send voice call for critical alerts')),
                ('slack_notification', models.BooleanField(default=False, help_text='Send Slack notifications')),
                ('cooldown_minutes', models.IntegerField(default=30, help_text='Minutes to wait before re-alerting')),
                ('last_triggered', models.DateTimeField(blank=True, help_text='Last time this alert was triggered', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Threshold',
                'verbose_name_plural': 'Alert Thresholds',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_value', models.FloatField(help_text='Value that triggered the alert')),
                ('message', models.TextField(help_text='Alert message')),
                ('severity', models.CharField(help_text='Alert severity at time of trigger', max_length=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('voice_sent', models.BooleanField(default=False)),
                ('slack_sent', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_minutes', models.IntegerField(blank=True, help_text='Minutes to acknowledge', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to=settings.AUTH_USER_MODEL)),
                ('alert_threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='optimization_api.alertthreshold')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS and voice alerts (format: +1234567890)', max_length=20)),
                ('slack_webhook', models.URLField(blank=True, help_text='Slack webhook URL for notifications')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for alerts')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('voice_notifications', models.BooleanField(default=False, help_text='Receive voice call notifications for critical alerts')),
                ('slack_notifications', models.BooleanField(default=False, help_text='Receive Slack notifications')),
                ('alert_cooldown_override', models.IntegerField(default=30, help_text='Default cooldown period in minutes for all alerts')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no non-critical alerts)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('default_tab', models.CharField(default='dashboard', max_length=20)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
