# Generated by Django 5.2.1 on 2025-05-28 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0002_systemstatus_alertthreshold_alertlog_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Optimization Profile', 'verbose_name_plural': 'User Optimization Profiles'},
        ),
        migrations.RenameField(
            model_name='alertlog',
            old_name='slack_sent',
            new_name='browser_shown',
        ),
        migrations.RemoveField(
            model_name='alertlog',
            name='response_time_minutes',
        ),
        migrations.RemoveField(
            model_name='alertlog',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='alertlog',
            name='voice_sent',
        ),
        migrations.RemoveField(
            model_name='alertthreshold',
            name='slack_notification',
        ),
        migrations.RemoveField(
            model_name='alertthreshold',
            name='sms_notification',
        ),
        migrations.RemoveField(
            model_name='alertthreshold',
            name='voice_notification',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alert_cooldown_override',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quiet_hours_start',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='slack_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='slack_webhook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='voice_notifications',
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='browser_notification',
            field=models.BooleanField(default=True, help_text='Show browser notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_check_interval',
            field=models.IntegerField(default=5, help_text='Alert checking interval in minutes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='browser_notifications',
            field=models.BooleanField(default=True, help_text='Receive browser notifications'),
        ),
        migrations.AlterField(
            model_name='alertthreshold',
            name='parameter',
            field=models.CharField(choices=[('afterbay_elevation', 'Afterbay Elevation (ft)'), ('oxph_power', 'OXPH Power (MW)'), ('r4_flow', 'R4 Flow (CFS)'), ('r30_flow', 'R30 Flow (CFS)'), ('mfra_power', 'MFRA Power (MW)'), ('float_level', 'Float Level (ft)'), ('net_flow', 'Net Flow (CFS)'), ('spillage', 'Spillage (AF)')], help_text='Parameter to monitor', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark theme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_tab',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('optimization', 'Optimization'), ('parameters', 'Parameters'), ('data', 'Data Table'), ('history', 'Historical Analysis'), ('prices', 'Electricity Prices'), ('rafting', 'Rafting Info')], default='dashboard', max_length=20),
        ),
        migrations.CreateModel(
            name='OptimizationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this parameter set', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default parameters')),
                ('abay_min_elev_ft', models.FloatField(default=1168.0, help_text='ABAY minimum elevation (ft)', validators=[django.core.validators.MinValueValidator(1160.0), django.core.validators.MaxValueValidator(1180.0)])),
                ('abay_max_elev_buffer_ft', models.FloatField(default=0.3, help_text='ABAY maximum elevation buffer (ft)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('abay_elev_per_af', models.FloatField(default=0.0132, help_text='ABAY elevation per acre-foot', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.02)])),
                ('oxph_min_mw', models.FloatField(default=0.8, help_text='OXPH minimum MW', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('oxph_max_mw', models.FloatField(default=5.8, help_text='OXPH maximum MW', validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(7.0)])),
                ('oxph_ramp_rate', models.FloatField(default=0.042, help_text='OXPH ramp rate (MW/min)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.1)])),
                ('spillage_penalty_weight', models.FloatField(default=10000.0, help_text='Spillage penalty weight', validators=[django.core.validators.MinValueValidator(1000.0), django.core.validators.MaxValueValidator(50000.0)])),
                ('summer_mw_reward_weight', models.FloatField(default=1000.0, help_text='Summer MW reward weight', validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(5000.0)])),
                ('base_smoothing_penalty', models.FloatField(default=100.0, help_text='Base smoothing penalty', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('summer_target_start_time', models.TimeField(default='08:00', help_text='Summer target start time')),
                ('summer_oxph_target_mw', models.FloatField(default=5.8, help_text='Summer OXPH target MW', validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(6.0)])),
                ('water_year_type', models.CharField(choices=[('Wet', 'Wet'), ('Above Normal', 'Above Normal'), ('Below Normal', 'Below Normal'), ('Dry', 'Dry'), ('Critical', 'Critical'), ('Extreme Critical', 'Extreme Critical')], default='Below Normal', help_text='Current water year classification', max_length=20)),
                ('rafting_season_end_date', models.DateField(default='2025-09-30', help_text='End of rafting season')),
                ('oxph_target_mw_rafting', models.FloatField(default=5.8, help_text='OXPH target MW during rafting', validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(6.0)])),
                ('early_release_dates', models.TextField(blank=True, help_text='Early release Saturday dates (YYYY-MM-DD, one per line)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Optimization Parameters',
                'verbose_name_plural': 'Optimization Parameters',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
