# Generated by Django 5.2.1 on 2025-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='voice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='sms_notification',
            field=models.BooleanField(default=False, help_text='Send SMS notifications'),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='voice_notification',
            field=models.BooleanField(default=False, help_text='Make voice calls for critical alerts'),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='alerts_triggered_count',
            field=models.IntegerField(default=0, help_text='Number of alerts triggered in this check'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS alerts (format: +1234567890)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refresh_interval',
            field=models.IntegerField(default=60, help_text='Dashboard refresh interval in seconds'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications for critical alerts'),
        ),
    ]
