# Generated by Django 5.2.1 on 2025-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0004_alertlog_sms_sent_alertlog_voice_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Last time user was active', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last login time', null=True),
        ),
    ]
