# Generated by Django 5.2.1 on 2025-05-30 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0005_userprofile_last_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertthreshold',
            name='category',
            field=models.CharField(choices=[('flow', 'Flow Alerts'), ('afterbay', 'Afterbay Alerts'), ('rafting', 'Rafting Alerts'), ('generation', 'Generation Alerts'), ('general', 'General Alerts')], default='general', help_text='Alert category for grouping', max_length=20),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='last_known_value',
            field=models.FloatField(blank=True, help_text='Last known value for change detection', null=True),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional configuration for special alert types'),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='special_type',
            field=models.CharField(choices=[('standard', 'Standard Alert'), ('rafting_ramp', 'Rafting Ramp Alert'), ('float_change', 'Float Level Change'), ('deviation', 'Deviation Alert')], default='standard', help_text='Special alert type requiring custom logic', max_length=20),
        ),
        migrations.CreateModel(
            name='RaftingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of rafting schedule')),
                ('start_time', models.TimeField(help_text='Rafting start time')),
                ('end_time', models.TimeField(help_text='Rafting end time')),
                ('is_early_release', models.BooleanField(default=False)),
                ('target_mw', models.FloatField(default=5.8, help_text='Target OXPH MW for rafting')),
                ('ramp_up_minutes', models.IntegerField(default=90, help_text='Minutes needed to ramp up')),
                ('ramp_down_minutes', models.IntegerField(default=30, help_text='Minutes needed to ramp down')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'created_by')},
            },
        ),
    ]
