# Generated by Django 5.2.1 on 2025-06-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0006_alertthreshold_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='solver_diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
