# Generated by Django 4.2.7 on 2025-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimization_api", "0007_optimizationrun_solver_diagnostics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="abay_delta_af_sim",
            new_name="abay_delta_af",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="simulated_abay_elev_ft",
            new_name="abay_elev_ft",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="abay_net_flow_cfs_recalc",
            new_name="abay_net_flow_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="mf1_2_cfs_sim",
            new_name="mf1_2_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="mf1_2_mw_sim",
            new_name="mf1_2_mw",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="mfra_forecast_mw",
            new_name="mfra_mw",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="oxph_schedule_mw",
            new_name="oxph_generation_mw",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="oxph_cfs_sim",
            new_name="oxph_outflow_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="r20_minus_r5l_forecast_cfs",
            new_name="r20_minus_r5l_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="r26_forecast_cfs",
            new_name="r26_flow_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="r30_forecast_cfs",
            new_name="r30_flow_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="r4_forecast_cfs",
            new_name="r4_flow_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="r5l_forecast_cfs",
            new_name="r5l_flow_cfs",
        ),
        migrations.RenameField(
            model_name="optimizationresult",
            old_name="spill_volume_af_recalc",
            new_name="spill_volume_af",
        ),
        migrations.RemoveField(
            model_name="optimizationresult",
            name="simulated_abay_af",
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="abay_af",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="abay_float_ft",
            field=models.FloatField(blank=True, null=True),
        ),
    ]