# Generated by Django 4.2.7 on 2025-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "optimization_api",
            "0008_rename_abay_delta_af_sim_optimizationresult_abay_delta_af_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PIDatum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_utc", models.DateTimeField(unique=True)),
                ("abay_elevation_ft", models.FloatField(blank=True, null=True)),
                ("abay_float_ft", models.FloatField(blank=True, null=True)),
                ("oxph_generation_mw", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["timestamp_utc"],
            },
        ),
    ]