# Generated by Django 4.2.7 on 2025-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimization_api", "0009_pidatum"),
    ]

    operations = [
        migrations.AddField(
            model_name="pidatum",
            name="ccs_mode",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="mfp_total_gen_mw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="oxph_setpoint_mw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="r20_flow_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="r26_flow_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="r30_flow_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="r4_flow_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pidatum",
            name="r5l_flow_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
    ]