# Generated by Django 4.2.7 on 2025-09-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimization_api", "0010_pidatum_ccs_mode_pidatum_mfp_total_gen_mw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationresult",
            name="abay_net_actual_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="abay_net_expected_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="abay_net_expected_cfs_no_bias",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="abay_net_expected_cfs_with_bias",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="bias_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="expected_abay_af",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="expected_abay_ft",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="head_limit_mw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="is_forecast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="mfra_side_reduction_mw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optimizationresult",
            name="regulated_component_cfs",
            field=models.FloatField(blank=True, null=True),
        ),
    ]