# Generated by Django 4.2.7 on 2026-02-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0013_sync_raw_values_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAISODAAwardSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(help_text='CAISO market delivery date')),
                ('interval_start_utc', models.DateTimeField(help_text='Hour start in UTC')),
                ('total_mw', models.FloatField(help_text='Sum of all MFP1 energy awards for this hour')),
                ('resource_count', models.IntegerField(default=1, help_text='Number of resources contributing')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade_date', 'interval_start_utc'],
                'unique_together': {('trade_date', 'interval_start_utc')},
            },
        ),
        migrations.CreateModel(
            name='CAISODAAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(help_text='CAISO market delivery date')),
                ('interval_start_utc', models.DateTimeField(help_text='Hour start in UTC')),
                ('interval_end_utc', models.DateTimeField(help_text='Hour end in UTC')),
                ('resource', models.CharField(help_text='Resource name, e.g. MDFK_2_UNIT 1', max_length=100)),
                ('mw', models.FloatField(help_text='Awarded MW')),
                ('product_type', models.CharField(default='EN', max_length=20)),
                ('schedule_type', models.CharField(default='FINAL', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trade_date', 'interval_start_utc'],
                'unique_together': {('trade_date', 'interval_start_utc', 'resource', 'product_type')},
            },
        ),
    ]
