# Generated by Django 4.2.7 on 2026-03-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_api', '0014_caisodaawardsummary_caisodaaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertthreshold',
            name='is_armed',
            field=models.BooleanField(default=True, help_text='False after alert fires; re-arms when value returns to safe zone'),
        ),
        migrations.AlterField(
            model_name='alertthreshold',
            name='parameter',
            field=models.CharField(choices=[('afterbay_elevation', 'Afterbay Elevation (ft)'), ('oxph_power', 'OXPH Power (MW)'), ('r4_flow', 'R4 Flow (CFS)'), ('r11_flow', 'R11 Flow (CFS)'), ('r30_flow', 'R30 Flow (CFS)'), ('mfra_power', 'MFRA Power (MW)'), ('mf_rt_vs_da', 'MF RT vs DA Deviation (MW)'), ('abay_forecast_deviation', 'ABAY Forecast Deviation (ft)'), ('float_level', 'Float Level (ft)'), ('net_flow', 'Net Flow (CFS)'), ('spillage', 'Spillage (AF)')], help_text='Parameter to monitor', max_length=30),
        ),
        migrations.AlterField(
            model_name='alertthreshold',
            name='special_type',
            field=models.CharField(choices=[('standard', 'Standard Alert'), ('rafting_ramp', 'Rafting Ramp Alert'), ('float_change', 'Float Level Change'), ('deviation', 'Deviation Alert'), ('mf_rt_vs_da', 'MF RT vs DA Deviation'), ('abay_forecast_dev', 'ABAY Forecast Deviation')], default='standard', help_text='Special alert type requiring custom logic', max_length=20),
        ),
    ]
